{{- if not ( include "agent.accessKeySecret" . ) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "agent.fullname" . }}
  namespace: {{ .Values.global.clusterConfig.namespace | default .Release.Namespace }}
  labels:
{{ include "agent.labels" . | indent 4 }}
type: Opaque
data:
 access-key : {{ include "agent.accessKey" . | b64enc | quote }}
{{- end }}
