{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "agent.serviceAccountName" .}}
  namespace: {{ .Values.global.clusterConfig.namespace | default .Release.Namespace }}
  labels:
{{ include "agent.labels" . | indent 4 }}
{{- end }}
